package simu.framework;
import eduni.distributions.*;
import simu.model.TapahtumanTyyppi;

/**
 * The `Saapumisprosessi` class in the framework models the arrival process in a simulation, using a continuous distribution generator to schedule new events based on event type and timing, and adds them to the event list for processing.
 */


public class Saapumisprosessi {
	
	private ContinuousGenerator generaattori;
	private Tapahtumalista tapahtumalista;
	private TapahtumanTyyppi tyyppi;

	/**
	 * Constructs an instance of the arrival process simulation.
	 * @param g The continuous distribution generator to simulate time between arrivals.
	 * @param tl The event list where new simulation events are added.
	 * @param tyyppi The type of the events to be generated by this process.
	 */

	public Saapumisprosessi(ContinuousGenerator g, Tapahtumalista tl, TapahtumanTyyppi tyyppi){
		this.generaattori = g;
		this.tapahtumalista = tl;
		this.tyyppi = tyyppi;
	}

	/**
	 * Generates the next event based on the arrival process and adds it to the event list.
	 * The time for the next event is determined by the current simulation time plus
	 * a sample time from the distribution generator.
	 */

	public void generoiSeuraava(){
		Tapahtuma t = new Tapahtuma(tyyppi, Kello.getInstance().getAika()+generaattori.sample());
		tapahtumalista.lisaa(t);
	}

}
