package eduni.distributions;

/** A random number generator based on the pascal distribution.
  * automatically generated by <code>MetaGenerator</code> 
  * @version 1.0, Thu Oct 03 11:00:47 BST 2002
  * @author F.Mallet from C.Simatos's original
  */

public class Pascal extends Generator implements DiscreteGenerator {
    private double prob;
    private int successes;
    /**
     * the seed is aumatically provided by the <code>SeedGenerator</code>
     */
    public Pascal(double prob, int successes) {
        super();
        set(prob, successes);
    }

    /**
     * The constructor with which a specific seed is set for the random
     * number generator
     * @param seed The initial seed for the generator, two instances with
     *             the same seed will generate the same sequence of numbers
     */
    public Pascal(double prob, int successes, long seed) {
        super(seed);
        set(prob, successes);
    }

    private void set(double prob, int successes) {
        if (prob<=0 || prob>=1)
            throw new ParameterException("Pascal: The probability of success must be between 0 and 1.");
        if (successes<=0)
            throw new ParameterException("Pascal: The number of successes must be a positive integer.");
        this.prob = prob;
        this.successes = successes;
    }

    /**
     * Generate a new random number.
     * @return The next random number in the sequence
     */
    public long sample() { 
         return distrib.pascal(prob, successes);
    }
}
